
<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Language;


class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
     public function run(): void
    {
       $languages  = [
            ['code' => 'name', 'english' => 'Name', 'arabic' => 'الاسم'],
            ['code' => 'email', 'english' => 'Email', 'arabic' => 'البريد الإلكتروني'],
            ['code' => 'phone', 'english' => 'Phone', 'arabic' => 'رقم الهاتف'],
            ['code' => 'address', 'english' => 'Address', 'arabic' => 'العنوان'],
            ['code' => 'city', 'english' => 'City', 'arabic' => 'المدينة'],
            ['code' => 'country', 'english' => 'Country', 'arabic' => 'الدولة'],
            ['code' => 'dob', 'english' => 'Date of Birth', 'arabic' => 'تاريخ الميلاد'],
            ['code' => 'gender', 'english' => 'Gender', 'arabic' => 'الجنس'],
            ['code' => 'password', 'english' => 'Password', 'arabic' => 'كلمة المرور'],
            ['code' => 'confirm_password', 'english' => 'Confirm Password', 'arabic' => 'تأكيد كلمة المرور'],
            ['code' => 'training', 'english' => 'Training', 'arabic' => 'تمرين'],
            ['code' => 'mentorship', 'english' => 'Mentorship', 'arabic' => 'الإرشاد'],
            ['code' => 'assessment', 'english' => 'Assessment', 'arabic' => 'تقدير'],
            ['code' => 'coaching', 'english' => 'Coaching', 'arabic' => 'التدريب'],
            ['code' => 'notifications', 'english' => 'Notifications', 'arabic' => 'إشعارات'],
            ['code' => 'view_all', 'english' => 'View All', 'arabic' => 'عرض الكل'],
            ['code' => 'view_records_found', 'english' => 'No Records Found', 'arabic' => 'لم يتم العثور على سجلات'],
            ['code' => 'profile', 'english' => 'Profile', 'arabic' => 'حساب تعريفي'],
            ['code' => 'my_profile', 'english' => 'My Profile', 'arabic' => 'ملفي الشخصي'],
            ['code' => 'logout', 'english' => 'Logout', 'arabic' => 'تسجيل الخروج'],
            ['code' => 'sign_in_sign_up', 'english' => 'Sign in / Sign up', 'arabic' => 'تسجيل الدخول / التسجيل'],
            ['code' => 'sign_in_as_jobseeker', 'english' => 'Sign in as Jobseeker', 'arabic' => 'تسجيل الدخول كباحث عن عمل'],
            ['code' => 'sign_in_as_mentor', 'english' => 'Sign in as Mentor', 'arabic' => 'تسجيل الدخول كباحث عن عمل'],
            ['code' => 'sign_in_as_trainer', 'english' => 'Sign in as Trainer', 'arabic' => 'تسجيل الدخول كباحث عن عمل'],
            ['code' => 'sign_in_as_assessor', 'english' => 'Sign in as Assessor', 'arabic' => 'تسجيل الدخول كباحث عن عمل'],
            ['code' => 'sign_in_as_coach', 'english' => 'Sign in as Coach', 'arabic' => 'تسجيل الدخول كباحث عن عمل'],
            ['code' => 'training_programs', 'english' => 'Training Programs', 'arabic' => 'برامج التدريب'],
            ['code' => 'trending_courses', 'english' => 'Trending Courses', 'arabic' => 'الدورات الشائعة'],
            ['code' => 'rating', 'english' => 'Rating', 'arabic' => 'التقييم'],
            ['code' => 'view_all_courses', 'english' => 'View All Courses', 'arabic' => 'عرض جميع الدورات'],
            ['code' => 'join_talentrek_intro', 'english' => 'Join Talentrek as a Trainer, Mentor, Assessor, and Coach', 'arabic' => 'انضم إلى Talentrek كمدرب ومرشد ومقيم ومدرب مهني'],
            ['code' => 'join_talentrek_desc', 'english' => 'Share your expertise, guide jobseeker/professional, and one stop-shop powerful platform.', 'arabic' => 'شارك خبراتك، ووجّه الباحثين عن عمل والمحترفين، ومنصة قوية شاملة لكل شيء.'],
            ['code' => 'empower_learners', 'english' => 'Empower Learners', 'arabic' => 'مكن المتعلمين'],
            ['code' => 'earn_and_grow', 'english' => 'Earn & Grow', 'arabic' => 'اكسب وتطور'],
            ['code' => 'flexible_engagement', 'english' => 'Flexible Engagement', 'arabic' => 'مرونة في المشاركة'],
            ['code' => 'expand_your_reach', 'english' => 'Expand Your Reach', 'arabic' => 'وسع نطاق وصولك'],
            ['code' => 'join_talentrek', 'english' => 'Join Talentrek', 'arabic' => 'انضم إلى Talentrek'],
            ['code' => 'what_people_are_saying', 'english' => 'What people are saying', 'arabic' => 'آراء الناس'],
            ['code' => 'student_worldwide', 'english' => 'Student worldwide', 'arabic' => 'طلاب من جميع أنحاء العالم'],
            ['code' => 'courses_available', 'english' => 'Course available', 'arabic' => 'الدورات المتاحة'],
            ['code' => 'people_loved_it', 'english' => 'People loved it', 'arabic' => 'أحبها الناس'],
            ['code' => 'explore', 'english' => 'Explore', 'arabic' => 'استكشاف'],
            ['code' => 'get_in_touch', 'english' => 'Get in Touch', 'arabic' => 'تواصل معنا'],
            ['code' => 'sign_in', 'english' => 'Sign in', 'arabic' => 'تسجيل الدخول'],
            ['code' => 'enter_details', 'english' => 'Please enter your details to continue', 'arabic' => 'الرجاء إدخال تفاصيلك للمتابعة'],
            ['code' => 'agree_terms', 'english' => 'I have read and agreed to', 'arabic' => 'لقد قرأت ووافقت على'],
            ['code' => 'terms_conditions', 'english' => 'terms and conditions', 'arabic' => 'الشروط والأحكام'],

            ['code' => 'signin_google', 'english' => 'Sign in with Google', 'arabic' => 'تسجيل الدخول باستخدام جوجل'],
            ['code' => 'no_account', 'english' => 'Don’t have an account?', 'arabic' => 'ليس لديك حساب؟'],
            ['code' => 'signup', 'english' => 'Sign up', 'arabic' => 'إنشاء حساب'],
            ['code' => 'forgot_password', 'english' => 'Forgot password?', 'arabic' => 'هل نسيت كلمة المرور؟'],
            ['code' => 'or', 'english' => 'or', 'arabic' => 'أو'],
            ['code' => 'have_account', 'english' => 'I have an account?', 'arabic' => 'هل لديك حساب؟'],
            ['code' => 'register', 'english' => 'Register', 'arabic' => 'تسجيل'],

            ['code' => 'filter', 'english' => 'Filter', 'arabic' => 'تصفية'],
            ['code' => 'course_topic', 'english' => 'Course topic', 'arabic' => 'موضوع الدورة'],
            ['code' => 'course_level', 'english' => 'Course level', 'arabic' => 'مستوى الدورة'],
            ['code' => 'training_type', 'english' => 'Training type', 'arabic' => 'نوع التدريب'],
            ['code' => 'search_here', 'english' => 'Search here', 'arabic' => 'ابحث هنا'],
            ['code' => 'showing', 'english' => 'Showing', 'arabic' => 'عرض'],
            ['code' => 'total_results', 'english' => 'total results', 'arabic' => 'إجمالي النتائج'],
            ['code' => 'previous', 'english' => 'Previous', 'arabic' => 'السابق'],
            ['code' => 'next', 'english' => 'Next', 'arabic' => 'التالي'],

            ['code' => 'mentors', 'english' => 'Mentors', 'arabic' => 'المرشدون'],
            ['code' => 'mentorship_overview', 'english' => 'Mentorship overview', 'arabic' => 'نظرة عامة على الإرشاد'],
            ['code' => 'mentor_role', 'english' => 'As a mentor, you play a pivotal role in shaping the future of your mentees\' careers. Your expertise, guidance, and support can have a profound impact on their professional growth and success.', 'arabic' => 'بصفتك مرشدًا، فإنك تلعب دورًا محوريًا في تشكيل مستقبل حياة المتدربين المهنية. يمكن أن يكون لخبرتك وتوجيهك ودعمك تأثير عميق على نموهم المهني ونجاحهم.'],
            ['code' => 'benefits_mentorship', 'english' => 'Benefits of mentorship', 'arabic' => 'فوائد الإرشاد'],

            ['code' => 'my_training', 'english' => 'My Training', 'arabic' => 'تدريبي'],
            ['code' => 'batch', 'english' => 'Batch', 'arabic' => 'دفعة'],
            ['code' => 'trainees', 'english' => 'Trainees', 'arabic' => 'المتدربون'],
            ['code' => 'chat_with_jobseeker', 'english' => 'Chat with jobseeker', 'arabic' => 'الدردشة مع الباحث عن عمل'],
            ['code' => 'reviews', 'english' => 'Reviews', 'arabic' => 'المراجعات'],
            ['code' => 'settings', 'english' => 'Settings', 'arabic' => 'الإعدادات'],
            ['code' => 'total_courses', 'english' => 'Total courses', 'arabic' => 'إجمالي الدورات'],
            ['code' => 'enrolled_jobseekers', 'english' => 'Enrolled jobseekers', 'arabic' => 'الباحثون عن عمل المسجلون'],
            ['code' => 'total_upcoming_batches', 'english' => 'Total upcoming batches', 'arabic' => 'إجمالي الدفعات القادمة'],
            ['code' => 'todays_batches', 'english' => "Today's batches", 'arabic' => 'دفعات اليوم'],
            ['code' => 'completed', 'english' => 'Completed', 'arabic' => 'مكتمل'],
            ['code' => 'pending', 'english' => 'Pending', 'arabic' => 'قيد الانتظار'],
            ['code' => 'list', 'english' => 'List', 'arabic' => 'قائمة'],
            ['code' => 'add', 'english' => 'Add', 'arabic' => 'إضافة'],
            ['code' => 'recorded_lecture', 'english' => 'Recorded Lecture', 'arabic' => 'محاضرة مسجلة'],
            ['code' => 'online_training', 'english' => 'Online Training', 'arabic' => 'تدريب عبر الإنترنت'],
            ['code' => 'offline_training', 'english' => 'Offline Training', 'arabic' => 'تدريب غير متصل'],
            ['code' => 'sr_no', 'english' => 'Sr. No.', 'arabic' => 'الرقم التسلسلي'],
            ['code' => 'title', 'english' => 'Title', 'arabic' => 'العنوان'],
            ['code' => 'price', 'english' => 'Price', 'arabic' => 'السعر'],
            ['code' => 'offer_price', 'english' => 'Offer Price', 'arabic' => 'السعر المخفض'],
            ['code' => 'action', 'english' => 'Action', 'arabic' => 'الإجراء'],
            ['code' => 'edit', 'english' => 'Edit', 'arabic' => 'تعديل'],
            ['code' => 'recorded_trainings', 'english' => 'Recorded Trainings', 'arabic' => 'الدورات المسجلة'],
            ['code' => 'online_trainings', 'english' => 'Online Trainings', 'arabic' => 'الدورات عبر الإنترنت'],
            ['code' => 'offline_trainings', 'english' => 'Offline Trainings', 'arabic' => 'الدورات غير المتصلة'],
            ['code' => 'online', 'english' => 'Online', 'arabic' => 'الإنترنت'],
            ['code' => 'offline', 'english' => 'Offline', 'arabic' => 'المتصلة'],
            ['code' => 'no_offline_trainings_found', 'english' => 'No offline trainings found.', 'arabic' => 'لم يتم العثور على تدريبات غير متصلة.'],
            ['code' => 'no_online_trainings_found', 'english' => 'No online trainings found.', 'arabic' => 'لم يتم العثور على تدريبات عبر الإنترنت.'],
            ['code' => 'no_recorded_trainings_found', 'english' => 'No recorded trainings found.', 'arabic' => 'لم يتم العثور على تدريبات مسجلة.'],
            ['code' => 'categories', 'english' => 'Categories', 'arabic' => 'الفئات'],
            ['code' => 'assessment_overview', 'english' => 'Assessment overview', 'arabic' => 'نظرة عامة على التقييم'],
            ['code' => 'benefits_assessment', 'english' => 'Benefits of Assessment', 'arabic' => 'فوائد التقييم'],
            ['code' => 'classroom', 'english' => 'Classroom', 'arabic' => 'الفصل الدراسي'],
            ['code' => 'course', 'english' => 'Course', 'arabic' => 'الدورة'],
            ['code' => 'course_title', 'english' => 'Course Title', 'arabic' => 'عنوان الدورة'],
            ['code' => 'enter_course_title', 'english' => 'Enter the Course Title', 'arabic' => 'أدخل عنوان الدورة'],
            ['code' => 'course_sub_title', 'english' => 'Course Sub Title', 'arabic' => 'العنوان الفرعي للدورة'],
            ['code' => 'enter_sub_title', 'english' => 'Enter the Sub Title', 'arabic' => 'أدخل العنوان الفرعي'],
            ['code' => 'training_objective', 'english' => 'Training Objective', 'arabic' => 'هدف التدريب'],
            ['code' => 'enter_training_objective', 'english' => 'Enter the Training Objective', 'arabic' => 'أدخل هدف التدريب'],
            ['code' => 'course_content', 'english' => 'Course Content', 'arabic' => 'محتوى الدورة'],
            ['code' => 'enter_course_content', 'english' => 'Enter the Course Content', 'arabic' => 'أدخل محتوى الدورة'],
            ['code' => 'select_level', 'english' => 'Select Level', 'arabic' => 'اختر المستوى'],
            ['code' => 'session_type', 'english' => 'Session Type', 'arabic' => 'نوع الجلسة'],
            ['code' => 'upload_thumbnail', 'english' => 'Upload Thumbnail', 'arabic' => 'تحميل الصورة المصغرة'],
            ['code' => 'course_price', 'english' => 'Course Price', 'arabic' => 'سعر الدورة'],
            ['code' => 'batch_details', 'english' => 'Batch Details', 'arabic' => 'تفاصيل الدفعة'],
            ['code' => 'batch_no', 'english' => 'Batch No', 'arabic' => 'رقم الدفعة'],
            ['code' => 'batch_date', 'english' => 'Batch Date', 'arabic' => 'تاريخ الدفعة'],
            ['code' => 'start_timing', 'english' => 'Start Timing', 'arabic' => 'وقت البدء'],
            ['code' => 'end_timing', 'english' => 'End Timing', 'arabic' => 'وقت الانتهاء'],
            ['code' => 'type', 'english' => 'Type', 'arabic' => 'النوع'],
            ['code' => 'duration', 'english' => 'Duration', 'arabic' => 'المدة'],
            ['code' => 'select_duration', 'english' => 'Select Duration', 'arabic' => 'اختر المدة'],
            ['code' => 'candidate', 'english' => 'Candidate', 'arabic' => 'المتدرب'],
            ['code' => 'strength', 'english' => 'Strength', 'arabic' => 'عدد المتدربين'],
            ['code' => 'select_days', 'english' => 'Select Days', 'arabic' => 'اختر الأيام'],
            ['code' => 'monday', 'english' => 'Monday', 'arabic' => 'الاثنين'],
            ['code' => 'tuesday', 'english' => 'Tuesday', 'arabic' => 'الثلاثاء'],
            ['code' => 'wednesday', 'english' => 'Wednesday', 'arabic' => 'الأربعاء'],
            ['code' => 'thursday', 'english' => 'Thursday', 'arabic' => 'الخميس'],
            ['code' => 'friday', 'english' => 'Friday', 'arabic' => 'الجمعة'],
            ['code' => 'saturday', 'english' => 'Saturday', 'arabic' => 'السبت'],
            ['code' => 'sunday', 'english' => 'Sunday', 'arabic' => 'الأحد'],
            ['code' => 'added_batches', 'english' => 'Added Batches', 'arabic' => 'الدفعات المضافة'],
            ['code' => 'start_date', 'english' => 'Start Date', 'arabic' => 'تاريخ البدء'],
            ['code' => 'end_date', 'english' => 'End Date', 'arabic' => 'تاريخ الانتهاء'],
            ['code' => 'time', 'english' => 'Time', 'arabic' => 'الوقت'],
            ['code' => 'days', 'english' => 'Days', 'arabic' => 'الأيام'],
            ['code' => 'delete', 'english' => 'Delete', 'arabic' => 'حذف'],
            ['code' => 'submit', 'english' => 'Submit', 'arabic' => 'إرسال'],
            ['code' => 'questions', 'english' => 'Questions', 'arabic' => 'الأسئلة'],
            ['code' => 'passing_percentage', 'english' => 'Passing Percentage', 'arabic' => 'نسبة النجاح'],
            ['code' => 'assign_course', 'english' => 'Assign Course', 'arabic' => 'تعيين دورة'],
            ['code' => 'create', 'english' => 'Create', 'arabic' => 'إنشاء'],
            ['code' => 'enter', 'english' => 'Enter', 'arabic' => 'أدخل'],
            ['code' => 'description', 'english' => 'description', 'arabic' => 'الوصف'],
            ['code' => 'select', 'english' => 'Select', 'arabic' => 'اختر'],
            ['code' => 'questionnaire', 'english' => 'Questionnaire', 'arabic' => 'استبيان'],
            ['code' => 'write_question_here', 'english' => 'Write your question here', 'arabic' => 'اكتب سؤالك هنا'],
            ['code' => 'make_correct_option', 'english' => 'Make correct option', 'arabic' => 'اجعل هذا الخيار صحيحًا'],
            ['code' => 'option', 'english' => 'Option', 'arabic' => 'خيار'],
            ['code' => 'batch_name', 'english' => 'Batch Name', 'arabic' => 'اسم الدفعة'],
            ['code' => 'course_name', 'english' => 'Course Name', 'arabic' => 'اسم الدورة'],
            ['code' => 'enrolled_students', 'english' => 'Enrolled Students', 'arabic' => 'الطلاب المسجلين'],
            ['code' => 'message', 'english' => 'Message', 'arabic' => 'رسالة'],
            ['code' => 'welcome_trainer_chat', 'english' => 'Welcome to the Trainer Chat Panel', 'arabic' => 'مرحبًا بك في لوحة دردشة المدرب'],
            ['code' => 'select_contact', 'english' => 'Select a contact from the left panel to view and send messages.', 'arabic' => 'اختر جهة اتصال من اللوحة اليسرى لعرض الرسائل وإرسالها.'],
            ['code' => 'payment_history', 'english' => 'Payment History', 'arabic' => 'سجل الدفع'],
            ['code' => 'paid_to', 'english' => 'Paid to', 'arabic' => 'مدفوع إلى'],
            ['code' => 'amount', 'english' => 'Amount', 'arabic' => 'المبلغ'],
            ['code' => 'payment_status', 'english' => 'Payment status', 'arabic' => 'حالة الدفع'],
            ['code' => 'view_invoice', 'english' => 'View Invoice', 'arabic' => 'عرض الفاتورة'],
            ['code' => 'subscription', 'english' => 'Subscription', 'arabic' => 'الاشتراك'],
            ['code' => 'subscription_plans', 'english' => 'Subscription Plans', 'arabic' => 'خطط الاشتراك'],
            ['code' => 'purchase_subscription', 'english' => 'Purchase subscription to get access to premium features', 'arabic' => 'اشترِ الاشتراك للوصول إلى الميزات المميزة'],
            ['code' => 'subscription_history', 'english' => 'Subscription History', 'arabic' => 'سجل الاشتراك'],
            ['code' => 'purchased_on', 'english' => 'Purchased on', 'arabic' => 'تم الشراء في'],
            ['code' => 'expired_on', 'english' => 'Expired on', 'arabic' => 'انتهت صلاحيته في'],
            ['code' => 'view_plans', 'english' => 'View Plans', 'arabic' => 'عرض الخطط'],
            ['code' => 'privacy_policy', 'english' => 'Privacy policy', 'arabic' => 'سياسة الخصوصية'],
            ['code' => 'delete_account', 'english' => 'Delete account', 'arabic' => 'حذف الحساب'],
            ['code' => 'remember_me', 'english' => 'Remember Me', 'arabic' => 'تذكرني'],
            ['code' => 'reset_password', 'english' => 'Reset Password', 'arabic' => 'إعادة تعيين كلمة المرور'],
            ['code' => 'send_password_reset_link', 'english' => 'Send Password Reset Link', 'arabic' => 'إرسال رابط إعادة تعيين كلمة المرور'],
            ['code' => 'dashboard', 'english' => 'Dashboard', 'arabic' => 'لوحة القيادة'],
            ['code' => 'welcome', 'english' => 'Welcome', 'arabic' => 'أهلا بك'],
            ['code' => 'edit_profile', 'english' => 'Edit Profile', 'arabic' => 'تعديل الملف الشخصي'],
            ['code' => 'change_password', 'english' => 'Change Password', 'arabic' => 'تغيير كلمة المرور'],
            ['code' => 'current_password', 'english' => 'Current Password', 'arabic' => 'كلمة المرور الحالية'],
            ['code' => 'new_password', 'english' => 'New Password', 'arabic' => 'كلمة مرور جديدة'],
            ['code' => 'confirm_new_password', 'english' => 'Confirm New Password', 'arabic' => 'تأكيد كلمة المرور الجديدة'],
            ['code' => 'update_password', 'english' => 'Update Password', 'arabic' => 	'تحديث كلمة المرور'],
            ['code' => 'save_changes', 'english' => 	'Save Changes', 	'arabic' => 	'حفظ التغييرات'],
            ['code' => 'cancel', 'english' => 'Cancel', 'arabic' => 'إلغاء'],
            ['code' => 'profile_updated_successfully', 'english' => 'Profile updated successfully', 'arabic' => 'تم تحديث الملف الشخصي بنجاح'],
            ['code' => 'password_updated_successfully', 'english' => 'Password updated successfully', 'arabic' => 'تم تحديث كلمة المرور بنجاح'],
            ['code' => 'invalid_current_password', 'english' => 'Invalid current password', 'arabic' => 'كلمة المرور الحالية غير صالحة'],
            ['code' => 'home', 'english' => 'Home', 'arabic' => 'الرئيسية'],
            ['code' => 'courses', 'english' => 'Courses', 'arabic' => 'الدورات'],
            ['code' => 'about_us', 'english' => 'About Us', 'arabic' => 'معلومات عنا'],
            ['code' => 'contact_us', 'english' => 'Contact Us', 'arabic' => 'اتصل بنا'],
            ['code' => 'full_stack_development', 'english' => 'Full Stack Development', 'arabic' => 'تطوير متكامل'],
            ['code' => 'data_science_ai', 'english' => 'Data Science and AI', 'arabic' => 'علم البيانات والذكاء الاصطناعي'],
            ['code' => 'ui_ux_design', 'english' => 'UI/UX Design', 'arabic' => 'تصميم واجهة وتجربة المستخدم'],
            ['code' => 'digital_marketing', 'english' => 'Degital Marketing', 'arabic' => 'التسويق الرقمي'],
            ['code' => 'project_management', 'english' => 'Project Management', 'arabic' => 'إدارة المشاريع'],
            ['code' => 'business_leaders', 'english' => 'Business Leaders', 'arabic' => 'قادة الأعمال'],
            ['code' => 'tech_experts', 'english' => 'Tech Experts', 'arabic' => 'خبراء التقنية'],
            ['code' => 'design_mentors', 'english' => 'Design Mentors', 'arabic' => 'مرشدو التصميم'],
            ['code' => 'startup', 'english' => 'Startup', 'arabic' => 'شركة ناشئة'],
            ['code' => 'faqs', 'english' => 'FAQS', 'arabic' => 'الأسئلة الشائعة'],
            ['code' => 'help_center', 'english' => 'Help Center', 'arabic' => 'مركز المساعدة'],
            ['code' => 'terms_of_use', 'english' => 'Term of Use', 'arabic' => 'شروط الاستخدام'],
            ['code' => 'subscribe_newsletter', 'english' => 'Subscribe to our newsletter', 'arabic' => 'اشترك في نشرتنا الإخبارية'],
            ['code' => 'enter_your_email', 'english' => 'Enter you email', 'arabic' => 'أدخل بريدك الإلكتروني'],
            ['code' => 'view_more', 'english' => 'view_more', 'arabic' => 'عرض المزيد'],
            ['code' => 'top_courses', 'english' => 'Top Courses', 'arabic' => 'أفضل الدورات'],
            ['code' => 'support', 'english' => 'Support', 'arabic' => 'الدعم'],
            ['code' => 'what_they_said', 'english' => 'What they said', 'arabic' => 'ماذا قالوا'],
            ['code' => 'sign_up', 'english' => 'Sign up', 'arabic' => 'تسجيل'],
            ['code' => 'mobile_number', 'english' => 'Mobile Number', 'arabic' => 'رقم الجوال'],
            ['code' => 'booking_slots', 'english' => 'Booking Slots', 'arabic' => 'حجوزات المواعيد'],
            ['code' => 'slots', 'english' => 'Slots', 'arabic' => 'المواعيد'],
            ['code' => 'available_subscription_plans', 'english' => 'Available Subscription Plans', 'arabic' => 'خطط الاشتراك المتاحة'],
            ['code' => 'buy', 'english' => 'Buy', 'arabic' => 'شراء'],
            ['code' => 'payment', 'english' => 'Payment', 'arabic' => 'الدفع'],
            ['code' => 'enter_card_details', 'english' => 'Enter your card details to continue', 'arabic' => 'أدخل تفاصيل بطاقتك للمتابعة'],
            ['code' => 'card_number', 'english' => 'Card Number', 'arabic' => 'رقم البطاقة'],
            ['code' => 'expiry', 'english' => 'Expiry', 'arabic' => 'تاريخ الانتهاء'],
            ['code' => 'cvv', 'english' => 'CVV', 'arabic' => 'الرمز السري (CVV)'],
            ['code' => 'pay_now', 'english' => 'Pay Now', 'arabic' => 'ادفع الآن'],
            ['code' => 'admin_support', 'english' => 'Admin support', 'arabic' => 'دعم الإدارة'],
            ['code' => 'ask_about_recruitment', 'english' => 'Ask anything about recruitment', 'arabic' => 'اسأل عن أي شيء يخص التوظيف'],
            ['code' => 'write_message_here', 'english' => 'Write your message here', 'arabic' => 'اكتب رسالتك هنا'],
            ['code' => 'total_upcoming_sessions', 'english' => 'Total upcoming sessions', 'arabic' => 'إجمالي الجلسات القادمة'],
            ['code' => 'todays_sessions', 'english' => 'Today’s sessions', 'arabic' => 'جلسات اليوم'],
            ['code' => 'upcoming_sessions', 'english' => 'Upcoming sessions', 'arabic' => 'الجلسات القادمة'],
            ['code' => 'cancelled_sessions', 'english' => 'Cancelled sessions', 'arabic' => 'الجلسات الملغاة'],
            ['code' => 'session', 'english' => 'Session', 'arabic' => 'جلسة'],
            ['code' => 'mode', 'english' => 'Mode', 'arabic' => 'الوضع'],
            ['code' => 'join', 'english' => 'Join', 'arabic' => 'انضم'],
            ['code' => 'view_feedback', 'english' => 'View Feedback', 'arabic' => 'عرض الملاحظات'],
            ['code' => 'view_cancel_reason', 'english' => 'View Cancel Reason', 'arabic' => 'عرض سبب الإلغاء'],
            ['code' => 'cancellation_reason', 'english' => 'Cancellation Reason', 'arabic' => 'سبب الإلغاء'],
            ['code' => 'reason', 'english' => 'Reason', 'arabic' => 'السبب'],
            ['code' => 'jobseekers_feedback', 'english' => 'Jobseekers feedback', 'arabic' => 'ملاحظات الباحثين عن عمل'],
            ['code' => 'reply', 'english' => 'Reply', 'arabic' => 'رد'],
            ['code' => 'cancel_this_session', 'english' => 'Cancel this session', 'arabic' => 'إلغاء هذه الجلسة'],
            ['code' => 'reason_for_cancellation', 'english' => 'Reason for cancellation', 'arabic' => 'سبب الإلغاء'],
            ['code' => 'write_here', 'english' => 'Write here', 'arabic' => 'اكتب هنا'],
            ['code' => 'postpone_session', 'english' => 'Postpone session', 'arabic' => 'تأجيل الجلسة'],
            ['code' => 'no', 'english' => 'No', 'arabic' => 'لا'],
            ['code' => 'yes', 'english' => 'Yes', 'arabic' => 'نعم'],
            ['code' => 'select_session_date', 'english' => 'Select session date', 'arabic' => 'اختر تاريخ الجلسة'],
            ['code' => 'select_session_time', 'english' => 'Select session time', 'arabic' => 'اختر وقت الجلسة'],
            ['code' => 'select_time', 'english' => 'Select time', 'arabic' => 'اختر الوقت'],
            ['code' => 'no_slots_available', 'english' => 'No slots available', 'arabic' => 'لا توجد مواعيد متاحة'],
            ['code' => 'cancel_session', 'english' => 'Cancel Session', 'arabic' => 'إلغاء الجلسة'],
            ['code' => 'reschedule', 'english' => 'Reschedule', 'arabic' => 'إعادة الجدولة'],
            ['code' => 'click_start_chat', 'english' => 'Click to start chat', 'arabic' => 'اضغط لبدء المحادثة'],
            ['code' => 'write_your_message', 'english' => 'Write your message', 'arabic' => 'اكتب رسالتك'],
            ['code' => 'welcome_chat_panel', 'english' => 'Welcome to the assessor Chat Panel', 'arabic' => 'مرحبًا بك في لوحة محادثة المقيم'],
            ['code' => 'select_contact_left_panel', 'english' => 'Select a contact from the left panel to view and send messages.', 'arabic' => 'اختر جهة اتصال من اللوحة اليسرى لعرض الرسائل وإرسالها.'],
            ['code' => 'create_time_slots', 'english' => 'Create time slots', 'arabic' => 'إنشاء مواعيد'],
            ['code' => 'select_coaching_mode', 'english' => 'Please select coaching mode.', 'arabic' => 'يرجى اختيار وضع التدريب.'],
            ['code' => 'select_start_end_time', 'english' => 'Please select both start and end time.', 'arabic' => 'يرجى اختيار وقت البداية والنهاية معًا.'],
            ['code' => 'start_end_same_error', 'english' => 'Start time and end time cannot be the same.', 'arabic' => 'لا يمكن أن يكون وقت البداية والنهاية متطابقين.'],
            ['code' => 'enter_registered_contact', 'english' => 'Please enter your registered mobile no. or email id', 'arabic' => 'يرجى إدخال رقم الهاتف المحمول أو البريد الإلكتروني المسجل.'],
            ['code' => 'enter_email_mobile', 'english' => 'Enter email or mobile number', 'arabic' => 'أدخل البريد الإلكتروني أو رقم الجوال'],
            ['code' => 'send_otp', 'english' => 'Send OTP', 'arabic' => 'إرسال رمز التحقق'],
            ['code' => 'mark_unavailable', 'english' => 'Mark unavailable', 'arabic' => 'تحديد كغير متاح'],
            ['code' => 'note_mark_unavailable', 'english' => 'Note: To mark the date unavailable, select the date and click on "Mark unavailable".', 'arabic' => 'ملاحظة: لتحديد التاريخ كغير متاح، اختر التاريخ واضغط على "تحديد كغير متاح".'],
            ['code' => 'online_mode', 'english' => 'Online Mode', 'arabic' => 'الوضع عبر الإنترنت'],
            ['code' => 'offline_mode', 'english' => 'Offline Mode', 'arabic' => 'الوضع دون اتصال'],
            ['code' => 'availability', 'english' => 'Availability', 'arabic' => 'التوفر'],
            ['code' => 'edit_slot_time', 'english' => 'Edit Slot Time', 'arabic' => 'تعديل وقت الموعد'],
            ['code' => 'update', 'english' => 'Update', 'arabic' => 'تحديث'],
            ['code' => 'confirm_deletion', 'english' => 'Confirm Deletion', 'arabic' => 'تأكيد الحذف'],
            ['code' => 'delete_slot_confirm', 'english' => 'Are you sure you want to delete this slot? This action cannot be undone.', 'arabic' => 'هل أنت متأكد أنك تريد حذف هذا الموعد؟ لا يمكن التراجع عن هذا الإجراء.'],
            ['code' => 'personal_information', 'english' => 'Personal information', 'arabic' => 'المعلومات الشخصية'],
            ['code' => 'educational_details', 'english' => 'Educational details', 'arabic' => 'التفاصيل التعليمية'],
            ['code' => 'work_experience', 'english' => 'Work experience', 'arabic' => 'الخبرة العملية'],
            ['code' => 'training_experience_skills', 'english' => 'Training Experience & Skills', 'arabic' => 'الخبرة التدريبية والمهارات'],
            ['code' => 'additional', 'english' => 'Additional', 'arabic' => 'إضافي'],
            ['code' => 'full_name', 'english' => 'Full Name', 'arabic' => 'الاسم الكامل'],
            ['code' => 'enter_full_name', 'english' => 'Enter full name', 'arabic' => 'أدخل الاسم الكامل'],
            ['code' => 'enter_email', 'english' => 'Enter email', 'arabic' => 'أدخل البريد الإلكتروني'],
            ['code' => 'phone_number', 'english' => 'Phone Number', 'arabic' => 'رقم الهاتف'],
            ['code' => 'enter_phone_number', 'english' => 'Enter Phone Number', 'arabic' => 'أدخل رقم الهاتف'],
            ['code' => 'national_id_number', 'english' => 'National ID Number', 'arabic' => 'رقم الهوية الوطنية'],
            ['code' => 'national_id_note', 'english' => 'National ID should start with 1 for male and 2 for female.', 'arabic' => 'يجب أن يبدأ رقم الهوية الوطنية بـ 1 للذكور و 2 للإناث.'],
            ['code' => 'enter_address', 'english' => 'Enter address', 'arabic' => 'أدخل العنوان'],
            ['code' => 'select_city', 'english' => 'Select city', 'arabic' => 'اختر المدينة'],
            ['code' => 'select_state', 'english' => 'Select state', 'arabic' => 'اختر الولاية'],
            ['code' => 'select_country', 'english' => 'Select country', 'arabic' => 'اختر الدولة'],
            ['code' => 'pin_code', 'english' => 'Pin Code', 'arabic' => 'الرمز البريدي'],
            ['code' => 'enter_pin_code', 'english' => 'Enter pin code', 'arabic' => 'أدخل الرمز البريدي'],
            ['code' => 'highest_qualification', 'english' => 'Highest qualification', 'arabic' => 'أعلى مؤهل'],
            ['code' => 'select_highest_qualification', 'english' => 'Select highest qualification', 'arabic' => 'اختر أعلى مؤهل'],
            ['code' => 'field_of_study', 'english' => 'Field of study', 'arabic' => 'مجال الدراسة'],
            ['code' => 'select_field_of_study', 'english' => 'Select field of study', 'arabic' => 'اختر مجال الدراسة'],
            ['code' => 'institution_name', 'english' => 'Institution name', 'arabic' => 'اسم المؤسسة'],
            ['code' => 'enter_institution_name', 'english' => 'Enter Institution name', 'arabic' => 'أدخل اسم المؤسسة'],
            ['code' => 'graduation_year', 'english' => 'Graduation year', 'arabic' => 'سنة التخرج'],
            ['code' => 'select_year_of_passing', 'english' => 'Select year of passing', 'arabic' => 'اختر سنة التخرج'],
            ['code' => 'add_education', 'english' => 'Add Education', 'arabic' => 'إضافة تعليم'],
            ['code' => 'back', 'english' => 'Back', 'arabic' => 'رجوع'],
            ['code' => 'job_title', 'english' => 'Job Title', 'arabic' => 'المسمى الوظيفي'],
            ['code' => 'organization', 'english' => 'Organization', 'arabic' => 'المؤسسة'],
            ['code' => 'started_from', 'english' => 'Started From', 'arabic' => 'بدأ من'],
            ['code' => 'to', 'english' => 'To', 'arabic' => 'إلى'],
            ['code' => 'currently_work_here', 'english' => 'I currently work here', 'arabic' => 'أعمل هنا حاليًا'],
            ['code' => 'add_work_experience', 'english' => 'Add Work Experience', 'arabic' => 'إضافة خبرة عملية'],
            ['code' => 'skills', 'english' => 'Skills', 'arabic' => 'المهارات'],
            ['code' => 'area_of_interest', 'english' => 'Area Of Interest', 'arabic' => 'مجال الاهتمام'],
            ['code' => 'select_area_of_interest', 'english' => 'Select Area of Interest', 'arabic' => 'اختر مجال الاهتمام'],
            ['code' => 'job_category', 'english' => 'Job Category', 'arabic' => 'فئة الوظيفة'],
            ['code' => 'website_link', 'english' => 'Website Link', 'arabic' => 'رابط الموقع'],
            ['code' => 'portfolio_link', 'english' => 'Portfolio Link', 'arabic' => 'رابط المعرض'],
            ['code' => 'upload_resume', 'english' => 'Upload resume', 'arabic' => 'تحميل السيرة الذاتية'],
            ['code' => 'upload_profile_picture', 'english' => 'Upload profile picture', 'arabic' => 'تحميل صورة الملف الشخصي'],
            ['code' => 'upload_training_certificate', 'english' => 'Upload training certificate', 'arabic' => 'تحميل شهادة التدريب'],
            ['code' => 'training_content', 'english' => 'Training content', 'arabic' => 'محتوى التدريب'],
            ['code' => 'course_overview', 'english' => 'Course overview', 'arabic' => 'نظرة عامة على الدورة'],
            ['code' => 'overview_not_available', 'english' => 'Overview not available.', 'arabic' => 'النظرة العامة غير متوفرة.'],
            ['code' => 'user_reviews_appear_here', 'english' => 'User reviews will appear here.', 'arabic' => 'ستظهر تقييمات المستخدمين هنا.'],
            ['code' => 'e_learning', 'english' => 'E learning', 'arabic' => 'التعلم الإلكتروني'],
            ['code' => 'chapter', 'english' => 'Chapter', 'arabic' => 'الفصل'],
            ['code' => 'video_player', 'english' => 'Video Player', 'arabic' => 'مشغل الفيديو'],
            ['code' => 'purchase_required', 'english' => 'Purchase Required', 'arabic' => 'الشراء مطلوب'],
            ['code' => 'must_purchase_course', 'english' => 'You must purchase this course to view the videos.', 'arabic' => 'يجب عليك شراء هذه الدورة لمشاهدة الفيديوهات.'],
            ['code' => 'close', 'english' => 'Close', 'arabic' => 'إغلاق'],
            ['code' => 'overall_rating', 'english' => 'Overall rating', 'arabic' => 'التقييم العام'],
            ['code' => 'write_review', 'english' => 'Write a review', 'arabic' => 'اكتب مراجعة'],
            ['code' => 'submit_review', 'english' => 'Submit Review', 'arabic' => 'إرسال المراجعة'],
            ['code' => 'buy_course', 'english' => 'Buy course', 'arabic' => 'شراء الدورة'],
            ['code' => 'download_training_certificate', 'english' => 'Download Training Certificate', 'arabic' => 'تحميل شهادة التدريب'],
            ['code' => 're_assessment', 'english' => 'Re-Assessment', 'arabic' => 'إعادة التقييم'],
            ['code' => 'not_available_yet', 'english' => 'Not Available Yet', 'arabic' => 'غير متاح بعد'],
            ['code' => 'visit', 'english' => 'Visit', 'arabic' => 'زيارة'],
            ['code' => 'buy_for_team', 'english' => 'Buy for Team', 'arabic' => 'شراء للفريق'],
            ['code' => 'add_to_cart', 'english' => 'Add to Cart', 'arabic' => 'أضف إلى السلة'],
            ['code' => 'go_to_cart', 'english' => 'Go to Cart', 'arabic' => 'اذهب إلى السلة'],
            ['code' => 'book_session', 'english' => 'Book Session', 'arabic' => 'حجز جلسة'],
            ['code' => 'no_slot_available', 'english' => 'No Slot Available', 'arabic' => 'لا يوجد موعد متاح'],
            ['code' => 'about_mentor', 'english' => 'About Mentor', 'arabic' => 'عن المرشد'],
            ['code' => 'bio_not_available', 'english' => 'Bio not available.', 'arabic' => 'السيرة الذاتية غير متوفرة.'],
            ['code' => 'qualification', 'english' => 'Qualification', 'arabic' => 'المؤهل'],
            ['code' => 'booking_id', 'english' => 'Booking ID', 'arabic' => 'رقم الحجز'],
            ['code' => 'appointment_success', 'english' => 'Your Appointment Booked Successfully', 'arabic' => 'تم حجز موعدك بنجاح'],
            ['code' => 'copy', 'english' => 'Copy', 'arabic' => 'نسخ'],
            ['code' => 'mentorship_mode', 'english' => 'Mentorship Mode', 'arabic' => 'وضع الإرشاد'],
            ['code' => 'select_date', 'english' => 'Select the Date', 'arabic' => 'اختر التاريخ'],
            ['code' => 'select_payment_method', 'english' => 'Select Payment Method', 'arabic' => 'اختر طريقة الدفع'],
            ['code' => 'credit_debit_card', 'english' => 'Credit / Debit Card', 'arabic' => 'بطاقة ائتمان / خصم'],
            ['code' => 'upi_online_payment', 'english' => 'UPI / Online Payment', 'arabic' => 'UPI / الدفع عبر الإنترنت'],
            ['code' => 'cardholder_name', 'english' => 'Cardholder Name', 'arabic' => 'اسم صاحب البطاقة'],
            ['code' => 'enter_upi_id', 'english' => 'Enter UPI ID', 'arabic' => 'أدخل معرف UPI'],
            ['code' => 'apply_promocode', 'english' => 'Apply Promocode', 'arabic' => 'تطبيق رمز الخصم'],
            ['code' => 'apply', 'english' => 'Apply', 'arabic' => 'تطبيق'],
            ['code' => 'mentor_session_billing', 'english' => 'Mentor Session Billing', 'arabic' => 'فاتورة جلسة المرشد'],
            ['code' => 'enter_promocode_discount', 'english' => 'Enter promocode for discount', 'arabic' => 'أدخل رمز الخصم للحصول على التخفيض'],
            ['code' => 'session_fee', 'english' => 'Session Fee', 'arabic' => 'رسوم الجلسة'],
            ['code' => 'discount', 'english' => 'Discount', 'arabic' => 'الخصم'],
            ['code' => 'total_payable', 'english' => 'Total Payable', 'arabic' => 'الإجمالي المستحق'],
            ['code' => 'tax', 'english' => 'Tax', 'arabic' => 'الضريبة'],
            ['code' => 'proceed_checkout', 'english' => 'Proceed to Checkout', 'arabic' => 'المتابعة إلى الدفع'],
            ['code' => 'about_coach', 'english' => 'About Coach', 'arabic' => 'عن المدرب'],
            ['code' => 'coach_session_billing', 'english' => 'Coach Session Billing', 'arabic' => 'فاتورة جلسة المدرب'],
            ['code' => 'about_assessor', 'english' => 'About Assessor', 'arabic' => 'عن المقيم'],
            ['code' => 'assessor_session_billing', 'english' => 'Assessor Session Billing', 'arabic' => 'فاتورة جلسة المقيم'],
            ['code' => 'terms_and_conditions', 'english' => 'Terms and Conditions', 'arabic' => 'الشروط والأحكام'],
            ['code' => 'training_mode', 'english' => 'Training mode', 'arabic' => 'وضع التدريب'],
            ['code' => 'select_training_mode', 'english' => 'Select Training mode', 'arabic' => 'اختر وضع التدريب'],
            ['code' => 'select_batch', 'english' => 'Select batch', 'arabic' => 'اختر الدفعة'],
            ['code' => 'timings', 'english' => 'Timings', 'arabic' => 'المواعيد'],
            ['code' => 'batch_started', 'english' => 'Batch has started', 'arabic' => 'بدأت الدفعة'],
            ['code' => 'batch_ended', 'english' => 'Batch ended', 'arabic' => 'انتهت الدفعة'],
            ['code' => 'batch_full', 'english' => 'Batch full', 'arabic' => 'الدفعة ممتلئة'],
            ['code' => 'no_batches_available', 'english' => 'No batches available.', 'arabic' => 'لا توجد دفعات متاحة.'],
            ['code' => 'billing_information', 'english' => 'Billing Information', 'arabic' => 'معلومات الفاتورة'],
            ['code' => 'course_total', 'english' => 'Course total', 'arabic' => 'إجمالي الدورة'],
            ['code' => 'saved_amount', 'english' => 'Saved amount', 'arabic' => 'المبلغ الموفر'],
            ['code' => 'total', 'english' => 'Total', 'arabic' => 'الإجمالي'],
            ['code' => 'number_of_members', 'english' => 'Number of members', 'arabic' => 'عدد الأعضاء'],
            ['code' => 'assessment_title', 'english' => 'Assessment Title', 'arabic' => 'عنوان التقييم'],
            ['code' => 'enter_assessment_title', 'english' => 'Enter assessment title', 'arabic' => 'أدخل عنوان التقييم'],
            ['code' => 'assessment_description', 'english' => 'Assessment description', 'arabic' => 'وصف التقييم'],
            ['code' => 'enter_description', 'english' => 'Enter description', 'arabic' => 'أدخل الوصف'],
            ['code' => 'assessment_level', 'english' => 'Assessment level', 'arabic' => 'مستوى التقييم'],
            ['code' => 'select_assessment_level', 'english' => 'Select assessment level', 'arabic' => 'اختر مستوى التقييم'],
            ['code' => 'intermediate', 'english' => 'Intermediate', 'arabic' => 'متوسط'],
            ['code' => 'advanced', 'english' => 'Advanced', 'arabic' => 'متقدم'],
            ['code' => 'create_questionnaire', 'english' => 'Create questionnaire', 'arabic' => 'إنشاء استبيان'],
            ['code' => 'add_option', 'english' => 'Add option', 'arabic' => 'إضافة خيار'],
            ['code' => 'add_question', 'english' => 'Add question', 'arabic' => 'إضافة سؤال'],
            ['code' => 'total_questions', 'english' => 'Total questions', 'arabic' => 'إجمالي الأسئلة'],
            ['code' => 'enter_total_questions', 'english' => 'Enter total questions', 'arabic' => 'أدخل إجمالي الأسئلة'],
            ['code' => 'mismatch_added_questions', 'english' => 'Mismatch with added questions.', 'arabic' => 'عدم التطابق مع الأسئلة المضافة.'],
            ['code' => 'passing_questions', 'english' => 'Passing questions', 'arabic' => 'أسئلة النجاح'],
            ['code' => 'enter_passing_questions', 'english' => 'Enter passing questions', 'arabic' => 'أدخل أسئلة النجاح'],
            ['code' => 'passing_cannot_exceed', 'english' => 'Passing questions cannot exceed total questions.', 'arabic' => 'لا يمكن أن تتجاوز أسئلة النجاح إجمالي الأسئلة.'],
            ['code' => 'training_level', 'english' => 'Training Level', 'arabic' => 'مستوى التدريب'],
            ['code' => 'months', 'english' => 'Months', 'arabic' => 'أشهر'],
            ['code' => 'years', 'english' => 'Years', 'arabic' => 'سنوات'],
            ['code' => 'time_conflict', 'english' => 'Time conflict with another batch.', 'arabic' => 'تعارض في الوقت مع دفعة أخرى.'],
            ['code' => 'recorded_course', 'english' => 'Recorded course', 'arabic' => 'دورة مسجلة'],
            ['code' => 'course_content_structure', 'english' => 'Course Content Structure', 'arabic' => 'هيكل محتوى الدورة'],
            ['code' => 'section_title', 'english' => 'Section title', 'arabic' => 'عنوان القسم'],
            ['code' => 'contents', 'english' => 'Contents', 'arabic' => 'المحتويات'],
            ['code' => 'add_content', 'english' => 'Add Content', 'arabic' => 'إضافة محتوى'],
            ['code' => 'course_videos', 'english' => 'Course Videos', 'arabic' => 'فيديوهات الدورة'],
            ['code' => 'upload', 'english' => 'Upload', 'arabic' => 'رفع'],
            ['code' => 'file_duration', 'english' => 'File Duration', 'arabic' => 'مدة الملف'],
            ['code' => 'enter_offer_price', 'english' => 'Enter Offer Price', 'arabic' => 'أدخل السعر المخفض'],
            ['code' => 'upload_file', 'english' => 'Upload File', 'arabic' => 'رفع الملف'],
            ['code' => 'add_training', 'english' => 'Add Training', 'arabic' => 'إضافة تدريب'],
            ['code' => 'page_of', 'english' => 'Page of', 'arabic' => 'صفحة من'],
            ['code' => 'no_batches_found', 'english' => 'No batches found.', 'arabic' => 'لم يتم العثور على دفعات.'],
            ['code' => 'enter_batch_no', 'english' => 'Enter batch no', 'arabic' => 'أدخل رقم الدفعة'],
            ['code' => 'batch_list', 'english' => 'Batch List', 'arabic' => 'قائمة الدفعات'],
            ['code' => 'before', 'english' => 'Before', 'arabic' => 'قبل'],
            ['code' => 'add_more_education', 'english' => 'Add More Education', 'arabic' => 'إضافة المزيد من التعليم'],
            ['code' => 'job_role', 'english' => 'Job Role', 'arabic' => 'الدور الوظيفي'],
            ['code' => 'training_experience', 'english' => 'Training Experience', 'arabic' => 'خبرة التدريب'],
            ['code' => 'training_skills', 'english' => 'Training Skills', 'arabic' => 'مهارات التدريب'],
            ['code' => 'enter_new_password', 'english' => 'Enter new password to reset the password', 'arabic' => 'أدخل كلمة مرور جديدة لإعادة تعيين كلمة المرور'],
            ['code' => 'jobseeker', 'english' => 'Jobseeker', 'arabic' => 'باحث عن عمل'],
            ['code' => 'review', 'english' => 'Review', 'arabic' => 'مراجعة'],
            ['code' => 'lessons', 'english' => 'Lessons', 'arabic' => 'دروس'],
            ['code' => 'enrollment_no', 'english' => 'Enrollment No', 'arabic' => 'رقم التسجيل'],
            ['code' => 'verify_otp', 'english' => 'Verify OTP', 'arabic' => 'تحقق من رمز التحقق'],
            ['code' => 'enter_otp', 'english' => 'Enter OTP sent on registered email or mobile no.', 'arabic' => 'أدخل رمز التحقق المرسل إلى البريد الإلكتروني أو الهاتف المسجل.'],
            ['code' => 'didnt_receive_otp', 'english' => 'Didn’t receive OTP?', 'arabic' => 'لم تستلم رمز التحقق؟'],
            ['code' => 'resend_otp', 'english' => 'Resend OTP', 'arabic' => 'إعادة إرسال رمز التحقق'],
            ['code' => 'otp_sent', 'english' => 'OTP Sent', 'arabic' => 'تم إرسال رمز التحقق'],
            ['code' => 'click_here', 'english' => 'Click here if not redirected', 'arabic' => 'انقر هنا إذا لم يتم إعادة توجيهك'],
            ['code' => 'assessment_results', 'english' => 'Assessment Results', 'arabic' => 'نتائج التقييم'],
            ['code' => 'review_answers', 'english' => 'Review your answers below. Correct answers are shown in green.', 'arabic' => 'راجع إجاباتك أدناه. الإجابات الصحيحة تظهر باللون الأخضر.'],
            ['code' => 'selected_answer', 'english' => 'Your selected answer is highlighted below.', 'arabic' => 'إجابتك المحددة مميزة أدناه.'],
            ['code' => 'next_question', 'english' => 'Next Question', 'arabic' => 'السؤال التالي'],
            ['code' => 'performance', 'english' => 'Performance', 'arabic' => 'الأداء'],
            ['code' => 'jump_to_question', 'english' => 'Jump To Question', 'arabic' => 'انتقال إلى السؤال'],
            ['code' => 'assessment_instructions', 'english' => 'Assessment Instructions', 'arabic' => 'تعليمات التقييم'],
            ['code' => 'start_assessment', 'english' => 'Start Assessment', 'arabic' => 'ابدأ التقييم'],
            ['code' => 'answer_questions', 'english' => 'Answer the following questions carefully.', 'arabic' => 'أجب على الأسئلة التالية بعناية.'],
            ['code' => 'select_option', 'english' => 'Select one option', 'arabic' => 'اختر خياراً واحداً'],
            ['code' => 'quiz_tracking', 'english' => 'Quiz Tracking', 'arabic' => 'تتبع الاختبار'],
            ['code' => 'time_remaining', 'english' => 'Time Remaining', 'arabic' => 'الوقت المتبقي'],
            ['code' => 'total_quiz_time', 'english' => 'Total Quiz Time', 'arabic' => 'الوقت الكلي للاختبار'],
            ['code' => 'quiz_navigation', 'english' => 'Quiz Navigation', 'arabic' => 'التنقل في الاختبار'],
            ['code' => 'finish_quiz', 'english' => 'Finish quiz', 'arabic' => 'إنهاء الاختبار'],
            ['code' => 'submit_quiz_confirm', 'english' => 'Are you sure you want to submit the quiz?', 'arabic' => 'هل أنت متأكد أنك تريد إرسال الاختبار؟'],
            ['code' => 'join_meet', 'english' => 'Join Meet', 'arabic' => 'انضم إلى الاجتماع'],
            ['code' => 'view_address', 'english' => 'View Address', 'arabic' => 'عرض العنوان'],
            ['code' => 'link_not_available', 'english' => 'Link not available', 'arabic' => 'الرابط غير متاح'],
            ['code' => 'mentor_address', 'english' => 'Mentor\'s Address', 'arabic' => 'عنوان المرشد'],
            ['code' => 'address_not_available', 'english' => 'Address not available', 'arabic' => 'العنوان غير متاح'],
            ['code' => 'join_zoom', 'english' => 'Join Zoom Meeting with', 'arabic' => 'انضم إلى اجتماع زووم مع'],
            ['code' => 'click_link_to_join', 'english' => 'Click the link below to join the meeting:', 'arabic' => 'انقر على الرابط أدناه للانضمام إلى الاجتماع:'],
            ['code' => 'no_assessment_sessions', 'english' => 'No assessment sessions found.', 'arabic' => 'لم يتم العثور على جلسات تقييم.'],
            ['code' => 'assessor_address', 'english' => 'Assessor\'s Address', 'arabic' => 'عنوان المقيم'],
            ['code' => 'no_coaching_sessions', 'english' => 'No coaching sessions found.', 'arabic' => 'لم يتم العثور على جلسات تدريب.'],
            ['code' => 'no_destination', 'english' => 'No destination available', 'arabic' => 'لا يوجد وجهة متاحة'],
            ['code' => 'coach_address', 'english' => 'Coach\'s Address', 'arabic' => 'عنوان المدرب'],
            ['code' => 'cart', 'english' => 'Cart', 'arabic' => 'السلة'],
            ['code' => 'certificates', 'english' => 'Certificates', 'arabic' => 'الشهادات'],
            ['code' => 'skills_training', 'english' => 'Skills & Training', 'arabic' => 'المهارات والتدريب'],
            ['code' => 'additional_information', 'english' => 'Additional Information', 'arabic' => 'معلومات إضافية'],
            ['code' => 'success', 'english' => 'Success!', 'arabic' => 'تم بنجاح!'],
            ['code' => 'coaching_overview', 'english' => 'Coaching overview', 'arabic' => 'نظرة عامة على التدريب'],
            ['code' => 'benefits_coaching', 'english' => 'Benefits coaching', 'arabic' => 'فوائد التدريب'],
            ['code' => 'sign_in_recruiter', 'english' => 'Sign in as Recruiter', 'arabic' => 'تسجيل الدخول كمُوظِّف'],
            ['code' => 'experience', 'english' => 'Experience', 'arabic' => 'الخبرة'],
            ['code' => 'arabic', 'english' => 'Arabic', 'arabic' => 'العربية'],
            ['code' => 'view_resume', 'english' => 'View Resume', 'arabic' => 'عرض السيرة الذاتية'],
            ['code' => 'english', 'english' => 'English', 'arabic' => 'الإنجليزية'],
            ['code' => 'upload_profile', 'english' => 'Upload Profile', 'arabic' => 'تحميل الملف الشخصي'],
            ['code' => 'view_profile', 'english' => 'View Profile', 'arabic' => 'عرض الملف الشخصي'],
            ['code' => 'delete_confirm', 'english' => 'Are you sure you want to delete', 'arabic' => 'هل أنت متأكد أنك تريد الحذف؟'],
            ['code' => 'male', 'english' => 'Male', 'arabic' => 'ذكر'],
            ['code' => 'female', 'english' => 'Female', 'arabic' => 'أنثى'],
            ['code' => 'mentor_information', 'english' => 'mentor information', 'arabic' => 'معلومات المرشد'],
            ['code' => 'mentor_overview', 'english' => 'mentor overview', 'arabic' => 'نظرة عامة عن المرشد'],
            ['code' => 'write_mentor', 'english' => 'Write about mentor', 'arabic' => 'اكتب عن المرشد'],
            ['code' => 'assessment_benefits', 'english' => 'Assessment benefits', 'arabic' => 'فوائد التقييم'],
            ['code' => 'write_assessment_benefits', 'english' => 'Write assessment benefits', 'arabic' => 'اكتب فوائد التقييم'],
            ['code' => 'your_profession', 'english' => 'Your profession', 'arabic' => 'مهنتك'],
            ['code' => 'enter_profession', 'english' => 'Enter your profession', 'arabic' => 'أدخل مهنتك'],
            ['code' => 'years_experience', 'english' => 'Years of experience', 'arabic' => 'سنوات الخبرة'],
            ['code' => 'price_per_session', 'english' => 'Price per session', 'arabic' => 'السعر لكل جلسة'],
            ['code' => 'enter_price', 'english' => 'Enter price per session', 'arabic' => 'أدخل السعر لكل جلسة'],
            ['code' => 'save_details', 'english' => 'Save details', 'arabic' => 'حفظ التفاصيل'],
            ['code' => 'select_start_time', 'english' => 'Select start time', 'arabic' => 'اختر وقت البدء'],
            ['code' => 'select_end_time', 'english' => 'Select end time', 'arabic' => 'اختر وقت الانتهاء'],
            ['code' => 'completed_sessions', 'english' => 'Completed  sessions', 'arabic' => 'الجلسات المكتملة'],
            ['code' => 'not_provided', 'english' => 'Not provided', 'arabic' => 'غير متوفر'],
            ['code' => 'shortlist', 'english' => 'Shortlist', 'arabic' => 'القائمة المختصرة'],
            ['code' => 'approved', 'english' => 'Approved', 'arabic' => 'تمت الموافقة'],
            ['code' => 'interview_requested', 'english' => 'Interview Requested', 'arabic' => 'تم طلب مقابلة'],
            ['code' => 'interview_request', 'english' => 'Interview Request', 'arabic' => 'طلب مقابلة'],
            ['code' => 'no_jobseekers', 'english' => 'No jobseekers match the selected filters.', 'arabic' => 'لا يوجد باحثون عن عمل يطابقون الفلاتر المحددة.'],
            ['code' => 'add_other_recruiters', 'english' => 'Add Other Recruiters', 'arabic' => 'إضافة موظفين آخرين'],
            ['code' => 'enter_name', 'english' => 'Enter name', 'arabic' => 'أدخل الاسم'],
            ['code' => 'enter_email', 'english' => 'Enter email', 'arabic' => 'أدخل البريد الإلكتروني'],
            ['code' => 'national_id', 'english' => 'National ID', 'arabic' => 'الهوية الوطنية'],
            ['code' => 'enter_national_id', 'english' => 'Enter National ID', 'arabic' => 'أدخل الهوية الوطنية'],
            ['code' => 'save_recruiters', 'english' => 'Save Recruiters', 'arabic' => 'حفظ الموظفين'],
            ['code' => 'subscription_expired', 'english' => 'Your subscription has expired.', 'arabic' => 'انتهى اشتراكك.'],
            ['code' => 'shortlisted', 'english' => 'Shortlisted', 'arabic' => 'تمت إضافته للقائمة المختصرة'],
            ['code' => 'interviews_scheduled', 'english' => 'Interviews scheduled', 'arabic' => 'تمت جدولة المقابلات'],
            ['code' => 'scheduled_interviews', 'english' => 'Scheduled Interviews', 'arabic' => 'المقابلات المجدولة'],
            ['code' => 'interview_date_time', 'english' => 'Interview Date/Time', 'arabic' => 'تاريخ/وقت المقابلة'],
            ['code' => 'not_scheduled', 'english' => 'Not Scheduled', 'arabic' => 'لم يتم الجدولة'],
            ['code' => 'interview_status', 'english' => 'Interview Status', 'arabic' => 'حالة المقابلة'],
            ['code' => 'interview_result', 'english' => 'Interview Result', 'arabic' => 'نتيجة المقابلة'],
            ['code' => 'share_feedback', 'english' => 'Share Feedback', 'arabic' => 'شارك الملاحظات'],
            ['code' => 'share_interview_feedback', 'english' => 'Share interview feedback', 'arabic' => 'شارك ملاحظات المقابلة'],
            ['code' => 'feedback', 'english' => 'Feedback', 'arabic' => 'ملاحظات'],
            ['code' => 'select_interview_status', 'english' => 'Select interview status', 'arabic' => 'اختر حالة المقابلة'],
            ['code' => 'pass', 'english' => 'Pass', 'arabic' => 'ناجح'],
            ['code' => 'fail', 'english' => 'Fail', 'arabic' => 'راسب'],
            ['code' => 'update_status', 'english' => 'Update Status', 'arabic' => 'تحديث الحالة'],
            ['code' => 'scheduled', 'english' => 'Scheduled', 'arabic' => 'تمت الجدولة'],
            ['code' => 'jobseeker_details', 'english' => 'Jobseeker Details', 'arabic' => 'تفاصيل الباحث عن عمل'],
            ['code' => 'skills_training2', 'english' => 'Skills and training', 'arabic' => 'المهارات والتدريب'],
            ['code' => 'ended_in', 'english' => 'Ended In', 'arabic' => 'انتهى في'],
            ['code' => 'cv_name', 'english' => 'CV Name', 'arabic' => 'اسم السيرة الذاتية'],
            ['code' => 'download_candidate_cv', 'english' => 'Download Candidate CV', 'arabic' => 'تحميل سيرة المرشح'],
            ['code' => 'download_cv', 'english' => 'Download CV', 'arabic' => 'تحميل السيرة الذاتية'],
            ['code' => 'candidates_experience', 'english' => 'Candidates experience', 'arabic' => 'خبرة المرشحين'],
            ['code' => 'fresher', 'english' => 'Fresher', 'arabic' => 'مبتدئ'],
            ['code' => 'all', 'english' => 'All', 'arabic' => 'الكل'],
            ['code' => 'education', 'english' => 'Education', 'arabic' => 'التعليم'],
            ['code' => 'certificate', 'english' => 'Certificate', 'arabic' => 'شهادة'],
            ['code' => 'not_certified', 'english' => 'Not certified', 'arabic' => 'غير معتمد'],
            ['code' => 'not_approved', 'english' => 'Not Approved', 'arabic' => 'لم تتم الموافقة'],
            ['code' => 'company_name', 'english' => 'Company name', 'arabic' => 'اسم الشركة'],
            ['code' => 'enter_company_name', 'english' => 'Enter company name', 'arabic' => 'أدخل اسم الشركة'],
            ['code' => 'company_website', 'english' => 'Company website', 'arabic' => 'موقع الشركة'],
            ['code' => 'enter_company_website', 'english' => 'Enter company website', 'arabic' => 'أدخل موقع الشركة'],
            ['code' => 'company_location', 'english' => 'Company location', 'arabic' => 'موقع الشركة'],
            ['code' => 'enter_company_location', 'english' => 'Enter company location', 'arabic' => 'أدخل موقع الشركة'],
            ['code' => 'company_address', 'english' => 'Company address', 'arabic' => 'عنوان الشركة'],
            ['code' => 'enter_company_address', 'english' => 'Enter company address', 'arabic' => 'أدخل عنوان الشركة'],
            ['code' => 'business_email', 'english' => 'Business email', 'arabic' => 'البريد الإلكتروني التجاري'],
            ['code' => 'enter_email_id', 'english' => 'Enter email id', 'arabic' => 'أدخل البريد الإلكتروني'],
            ['code' => 'company_phone_number', 'english' => 'Company phone number', 'arabic' => 'رقم هاتف الشركة'],
            ['code' => 'number_of_employees', 'english' => 'Number of employees', 'arabic' => 'عدد الموظفين'],
            ['code' => 'enter_number_of_employees', 'english' => 'Enter number of employees', 'arabic' => 'أدخل عدد الموظفين'],
            ['code' => 'industry_type', 'english' => 'Industry type', 'arabic' => 'نوع الصناعة'],
            ['code' => 'select_type', 'english' => 'Select type', 'arabic' => 'اختر النوع'],
            ['code' => 'company_registration_number', 'english' => 'Company registration number', 'arabic' => 'رقم تسجيل الشركة'],
            ['code' => 'cr_number', 'english' => 'CR number', 'arabic' => 'رقم السجل التجاري'],
            ['code' => 'enter_cr_number', 'english' => 'Enter CR number', 'arabic' => 'أدخل رقم السجل التجاري'],
            ['code' => 'recruiter_details', 'english' => 'Recruiter details', 'arabic' => 'تفاصيل الموظف'],
            ['code' => 'recruiters_name', 'english' => 'Recruiter\'s name', 'arabic' => 'اسم الموظف'],
            ['code' => 'enter_recruiters_name', 'english' => 'Enter recruiter\'s name', 'arabic' => 'أدخل اسم الموظف'],
            ['code' => 'recruiters_email', 'english' => 'Recruiter\'s email', 'arabic' => 'بريد الموظف'],
            ['code' => 'enter_recruiters_email', 'english' => 'Enter recruiter\'s email', 'arabic' => 'أدخل بريد الموظف'],
            ['code' => 'recruiters_phone_number', 'english' => 'Recruiter\'s phone number', 'arabic' => 'هاتف الموظف'],
            ['code' => 'enter_recruiters_phone_number', 'english' => 'Enter recruiter\'s phone_number', 'arabic' => 'أدخل هاتف الموظف'],
            ['code' => 'documents', 'english' => 'Documents', 'arabic' => 'الوثائق'],
            ['code' => 'company_profile_picture', 'english' => 'Company Profile Picuture', 'arabic' => 'صورة الملف الشخصي للشركة'],
            ['code' => 'company_registration_documents', 'english' => 'Company Registration Documents', 'arabic' => 'وثائق تسجيل الشركة'],
            ['code' => 'company_information', 'english' => 'Company Information', 'arabic' => 'معلومات الشركة'],
            ['code' => 'establishment_date', 'english' => 'Establishment Date', 'arabic' => 'تاريخ التأسيس'],
            ['code' => 'view_image', 'english' => 'View Image', 'arabic' => 'عرض الصورة'],
            ['code' => 'view_document', 'english' => 'View Document', 'arabic' => 'عرض المستند'],
            ['code' => 'registration_document', 'english' => 'Registration Document', 'arabic' => 'مستند التسجيل'],
        ];


        foreach ($languages as $lang) {
            Language::create($lang);
        }
    }
}
