<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;

use App\Models\AdditionalInfo;
use App\Models\Mentors;
class MentorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('mentors')->insert([
            [
                'name' => 'Anjali Verma',
                'email' => 'anjali@example.com',
                'national_id' => 'XYZ987654',
                'phone_code' => '+1',
                'phone_number' => '5551234567',
                'date_of_birth' => '1988-11-23',
                'city' => 'New York',
                'password' => Hash::make('securepass'),
                'pass' => 'securepass',
                'status' => 'active',
                'otp' => '654321',
                'admin_status' => 'superadmin_approved',
                'inactive_reason' => 'Profile incomplete',
                'rejection_reason' => null,
                'shortlist' => null,
                'admin_recruiter_status' => null,
                'google_id' => Str::uuid(),
                'avatar' => 'avatar2.png',
                'isSubscribtionBuy' => 'no',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ravi Sharma',
                'email' => 'ravi@example.com',
                'national_id' => 'ABC123456',
                'phone_code' => '+91',
                'phone_number' => '9876543210',
                'date_of_birth' => '1990-04-10',
                'city' => 'Delhi',
                'password' => Hash::make('pass123'),
                'pass' => 'pass123',
                'status' => 'pending',
                'otp' => '123456',
                'admin_status' => 'superadmin_approved',
                'inactive_reason' => null,
                'rejection_reason' => null,
                'shortlist' => null,
                'admin_recruiter_status' => null,
                'google_id' => Str::uuid(),
                'avatar' => 'avatar3.png',
                'isSubscribtionBuy' => 'no',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Meera Iyer',
                'email' => 'meera@example.com',
                'national_id' => 'DEF234567',
                'phone_code' => '+44',
                'phone_number' => '7700123456',
                'date_of_birth' => '1985-02-15',
                'city' => 'London',
                'password' => Hash::make('meera@2025'),
                'pass' => 'meera@2025',
                'status' => 'active',
                'otp' => '111111',
                'admin_status' => 'superadmin_approved',
                'inactive_reason' => null,
                'rejection_reason' => null,
                'shortlist' => null,
                'admin_recruiter_status' => 'approved',
                'google_id' => Str::uuid(),
                'avatar' => 'avatar4.png',
                'isSubscribtionBuy' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ali Khan',
                'email' => 'ali.khan@example.com',
                'national_id' => 'GHI345678',
                'phone_code' => '+971',
                'phone_number' => '501234567',
                'date_of_birth' => '1992-09-21',
                'city' => 'Dubai',
                'password' => Hash::make('aliSecure'),
                'pass' => 'aliSecure',
                'status' => 'inactive',
                'otp' => '222222',
                'admin_status' => 'superadmin_approved',
                'inactive_reason' => 'Document missing',
                'rejection_reason' => 'Invalid ID proof',
                'shortlist' => null,
                'admin_recruiter_status' => null,
                'google_id' => Str::uuid(),
                'avatar' => 'avatar5.png',
                'isSubscribtionBuy' => 'no',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sophia Lewis',
                'email' => 'sophia@example.com',
                'national_id' => 'JKL456789',
                'phone_code' => '+1',
                'phone_number' => '4045557890',
                'date_of_birth' => '1995-12-03',
                'city' => 'Los Angeles',
                'password' => Hash::make('sophiaPass'),
                'pass' => 'sophiaPass',
                'status' => 'active',
                'otp' => '333333',
                'admin_status' => 'superadmin_approved',
                'inactive_reason' => null,
                'rejection_reason' => null,
                'shortlist' => 'yes',
                'admin_recruiter_status' => null,
                'google_id' => Str::uuid(),
                'avatar' => 'avatar6.png',
                'isSubscribtionBuy' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rahul Patil',
                'email' => 'rahul.p@example.com',
                'national_id' => 'MNO567890',
                'phone_code' => '+91',
                'phone_number' => '7894561230',
                'date_of_birth' => '1983-06-30',
                'city' => 'Pune',
                'password' => Hash::make('rahulPass'),
                'pass' => 'rahulPass',
                'status' => 'active',
                'otp' => '444444',
                'admin_status' => 'superadmin_approved',
                'inactive_reason' => null,
                'rejection_reason' => null,
                'shortlist' => 'yes',
                'admin_recruiter_status' => 'approved',
                'google_id' => Str::uuid(),
                'avatar' => 'avatar7.png',
                'isSubscribtionBuy' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lina Wang',
                'email' => 'lina@example.com',
                'national_id' => 'PQR678901',
                'phone_code' => '+86',
                'phone_number' => '13800138000',
                'date_of_birth' => '1987-08-18',
                'city' => 'Beijing',
                'password' => Hash::make('lina123'),
                'pass' => 'lina123',
                'status' => 'pending',
                'otp' => '555555',
                'admin_status' => 'superadmin_approved',
                'inactive_reason' => null,
                'rejection_reason' => null,
                'shortlist' => null,
                'admin_recruiter_status' => null,
                'google_id' => Str::uuid(),
                'avatar' => 'avatar8.png',
                'isSubscribtionBuy' => 'no',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'David Green',
                'email' => 'david.g@example.com',
                'national_id' => 'STU789012',
                'phone_code' => '+61',
                'phone_number' => '412345678',
                'date_of_birth' => '1979-03-25',
                'city' => 'Sydney',
                'password' => Hash::make('davidSecure'),
                'pass' => 'davidSecure',
                'status' => 'inactive',
                'otp' => '666666',
                'admin_status' => 'superadmin_approved',
                'inactive_reason' => 'Inactive too long',
                'rejection_reason' => null,
                'shortlist' => null,
                'admin_recruiter_status' => null,
                'google_id' => Str::uuid(),
                'avatar' => 'avatar9.png',
                'isSubscribtionBuy' => 'no',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fatima Noor',
                'email' => 'fatima.noor@example.com',
                'national_id' => 'VWX890123',
                'phone_code' => '+92',
                'phone_number' => '3219876543',
                'date_of_birth' => '1994-07-09',
                'city' => 'Lahore',
                'password' => Hash::make('fatima2025'),
                'pass' => 'fatima2025',
                'status' => 'active',
                'otp' => '777777',
                'admin_status' => 'superadmin_approved',
                'inactive_reason' => null,
                'rejection_reason' => null,
                'shortlist' => null,
                'admin_recruiter_status' => 'approved',
                'google_id' => Str::uuid(),
                'avatar' => 'avatar10.png',
                'isSubscribtionBuy' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        $mentors = Mentors::all();

        foreach ($mentors as $mentor) {
            AdditionalInfo::create([
                'user_id' => $mentor->id,
                'user_type' => 'mentor',
                'doc_type' => 'mentor_profile_picture',
                'document_name' => 'mentor_profile_picture_' . $mentor->name . '.jpg',
                'document_path' => 'http://hancockogundiyapartners.com/wp-content/uploads/2019/07/dummy-profile-pic-300x300.jpg',
            ]);
        }

    }
}
